stages:
   - build
   - release

build_amd64:
 stage: build
 artifacts:
   name: "build_amd64"
   untracked: false
   expire_in: 60 mins
   paths:
       - $CI_PROJECT_DIR/ci_work/*.deb
       - $CI_PROJECT_DIR/ci_work/*.changes
       - $CI_PROJECT_DIR/ci_work/qundr-sec-ops/debian/changelog
 script:
   - echo "build"
   - curl http://172.17.21.15:10080/misc/ci_scripts/raw/master/build.sh | bash
 tags:
   - qne-qundr-sec-ops-builder

release_amd64:
 stage: release
 dependencies:
     - build_amd64
 script:
   - echo "repo"
   - curl http://172.17.21.15:10080/misc/ci_scripts/raw/master/repo.sh | sudo --preserve-env bash
 tags:
   - qne-qundr-sec-ops-publisher
