# useage 
# env $(cat /var/lib/qtraps-image/script/.env) docker-compose -f /var/lib/qtraps-image/script/docker-compose.yml -p $new_project_name up -d

version: "3"

services:
    qundr-sec-ops:
        image: "${IMAGE_TAG}"
        container_name: "qunder-sec-ops"
        environment:
            - KAPACITOR_HOSTNAME=kapacitor
            - KAPACITOR_INFLUXDB_0_URLS_0=http://127.0.0.1:8086
            - INFLUXDB_DB=ndr_management
        volumes: 
            - /var/run/influxdb:/var/run/influxdb
            - ${NDR_PATH}/${SEC_OPS_PATH}/conf/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
            - ${NDR_PATH}/${SEC_OPS_PATH}/conf/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
            - ${NDR_PATH}/log/${SEC_OPS_PATH}/:/var/log
        expose:
            - "8086"
            - "9092"

