# useage 
# env $(cat /.data/qne-qundr/sec-ops/.env) docker-compose -f /.data/qne-qundr/sec-ops/scripts/docker-compose.yml up -d

version: "3"

services:
    qundr-sec-ops:
        image: "${IMAGE_TAG}"
        container_name: "qundr-sec-ops"
        environment:
            - KAPACITOR_HOSTNAME=kapacitor
            - KAPACITOR_INFLUXDB_0_URLS_0=http://127.0.0.1:8086
        volumes: 
            - /var/run/influxdb:/var/run/influxdb
            - ${NDR_PATH}/${SEC_OPS_PATH}/conf/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
            - ${NDR_PATH}/${SEC_OPS_PATH}/conf/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
            - ${NDR_PATH}/log/${SEC_OPS_PATH}/:/var/log
            - ${NDR_PATH}/${SEC_OPS_PATH}/lib/:/var/lib/influxdb/
            - ${NDR_PATH}/${SEC_OPS_PATH}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ${NDR_PATH}/${SEC_OPS_PATH}/rules:/var/lib/rules
            - ${NDR_PATH}/${SEC_OPS_PATH}/rule_handler:/var/lib/rule_handler
            - /var/run:/var/run
        expose:
            - "8086"
            - "9092"
        extra_hosts:
            - "kapacitor:127.0.0.1"
        network_mode: bridge

