Document: qundr-sec-ops
Title: Debian qundr-sec-ops Manual
Author: <insert document author here>
Abstract: This manual describes what qundr-sec-ops is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qundr-sec-ops/qundr-sec-ops.sgml.gz

Format: postscript
Files: /usr/share/doc/qundr-sec-ops/qundr-sec-ops.ps.gz

Format: text
Files: /usr/share/doc/qundr-sec-ops/qundr-sec-ops.text.gz

Format: HTML
Index: /usr/share/doc/qundr-sec-ops/html/index.html
Files: /usr/share/doc/qundr-sec-ops/html/*.html
